# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-25 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180125_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
