# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-25 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
